### ISSUE TITLE
Error reported when executing on windows

### ISSUE THREAD

**Issue by Cc28256** [krabelize/icmpdoor#14]
1 Using binaries already available on github
2 windows 10
3 icmp-cnc.exe err ：
shell: usage: icmp-cnc.exe [-h] -d DESTINATION_IP
icmp-cnc.exe: error: the following arguments are required: -d/--destination_ip

why？
![image](https://github.com/krabelize/icmpdoor/assets/50364169/f01d642f-cbbe-4e5c-97c0-bf4cd1b57abe)

**Comment by krabelize** [comment]
Hi @Cc28256, the pre-compiled binary normally works on Windows clients. The screenshot of yours does not look a Windows cmd shell? Did you try via cmd and on another computer?

Syntax usage example: icmp-cnc.exe -d 10.10.10.10

**Comment by cookpoo78** [comment]
same problem here (with the pre-compiled binary)...
