### ISSUE TITLE
I've been trying to find a way to download this onto windows for some hours can ANYONE help me plz

### ISSUE THREAD

**Issue by buhnropp** [krabelize/icmpdoor#3]
How can I download 'icmpdoor' onto windows?

**Comment by krabelize** [comment]
[In the pre-compiled binaries folder](https://github.com/krabelize/icmpdoor/tree/main/binaries/x86_64-windows)

**Comment by buhnropp** [comment]
tried it, it doesn't work. It opens for 2 seconds, types something and then shuts itself off.

**Comment by krabelize** [comment]
Please create a new issue for each problem. I cannot help you if you with limit context. 

Please check your environmental variables, try another machine/VM, and read the blog post: https://cryptsus.com/blog/icmp-reverse-shell.html
