### ISSUE TITLE
python3 icmp 

### ISSUE THREAD

**Issue by AloneAndUnknown** [krabelize/icmpdoor#5]
Seems like i get a "
[+]ICMP C2 started!
shell: hostname
"
Edit: It appears this doesnt work if the victim is behind a NAT? when i tried with C2 and Victim as both having pub IP's it worked, but when it was behind the NAT, it did not.

**Comment by krabelize** [comment]
Hi @AloneAndUnknown, are you running the compiled binaries or the Python script? What is the host OS and the target OS?

**Comment by krabelize** [comment]
No reply for 1 month. Closing ticket.
