### ISSUE TITLE
Executable files for windows

### ISSUE THREAD

**Issue by iAmFoxik** [krabelize/icmpdoor#6]
How did you get the executables for windows? Do I understand correctly that they are not built with py2exe?

And one more question. Why didn't the executables ask for additional DLL packages? Did you build them into the exe or use any libraries when building the exe file?

**Comment by krabelize** [comment]
No, executables are build with pyinstaller. Yes, separate DLLs only make more noise in EDRs so I left them out.

**Comment by iAmFoxik** [comment]
Can I know which DLL files you included in the project? I was getting confused at this step.
